name: Problem
description: Open an issue before you start solving a problem
title: "[STATUS] [PLATFORM] - "
labels: ["problem"]
body:
  - type: checkboxes
    id: status
    attributes:
      label: Status
      description: Select one status (will be reflected in title and labels)
      options:
        - label: 진행 중
        - label: 보류
        - label: SOS
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 플랫폼
      description: 문제 플랫폼 선택
      options:
        - Baekjoon
        - Programmers
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: 티어
      description: 티어 선택
      options:
        - 브론즈
        - 실버
        - 골드
        - 플레

  - type: input
    id: problem_number
    attributes:
      label: Problem Number (Baekjoon only)
      description: Enter problem number if you chose Baekjoon
      placeholder: "1000"

  - type: input
    id: level
    attributes:
      label: Level
      description: Enter level (0 ~ 5) if you chose Programmers
      placeholder: "0"

  - type: input
    id: title
    attributes:
      label: 문제 이름 
      description: Enter problem title if you chose Programmers
      placeholder: "문제 이름"

