name: "Problem"
description: "Open an issue before you start solving a problem"
title: "[PROBLEM] <LV ?> - <title> "
labels: ["problem"]
body:
  - type: input
    id: level
    attributes:
      label: Level
      description: "0 ~ 5"
      placeholder: ""
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: "e.g 동전 던지기, 팽이 돌리기"
      placeholder: "Title"
    validations:
      required: true

  - type: checkboxes
    id: progress
    attributes:
      label: Progress
      description: "Update this as you go"
      options:
        - label: Read & understood the problem
        - label: Designed approach
        - label: Implemented solution
        - label: Passed sample tests
        - label: Finalized (cleanup + explanation)
